// The one recipe. agent/theme.json holds two colors — primary (the ink) and accent — and every other color for the
// web (CSS custom properties, light + dark), Mac (Swift) and Android (Kotlin, XML) is computed here. No platform mixes colors itself.
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const theme = JSON.parse(await readFile(new URL('../theme.json', import.meta.url), 'utf8'));
const hex = (value, name) => {
  if (!/^#[0-9a-fA-F]{6}$/.test(value)) throw new Error(`${name} must be #rrggbb`);
  return value.toLowerCase();
};
const primary = hex(theme.primary, 'primary'), accent = hex(theme.accent, 'accent');

// --- color math (sRGB, 0–255 channels; alpha 0–1) -------------------------------------------------------------
const rgb = (h) => ({ r: parseInt(h.slice(1, 3), 16), g: parseInt(h.slice(3, 5), 16), b: parseInt(h.slice(5, 7), 16), a: 1 });
const mix = (a, p, b) => ({ r: a.r * p + b.r * (1 - p), g: a.g * p + b.g * (1 - p), b: a.b * p + b.b * (1 - p), a: 1 });
const alpha = (c, a) => ({ ...c, a });
const luminance = ({ r, g, b }) => {
  const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
};
const WHITE = rgb('#ffffff'), BLACK = rgb('#000000'), P = rgb(primary), A = rgb(accent);

// Restraint (agentation.com): white surfaces, ink text, hairlines at a few percent, one accent used sparingly.
const darkSurface = mix(WHITE, 0.04, P);
const onAccent = luminance(A) > 0.4 ? mix(P, 0.85, BLACK) : WHITE;   // dark ink on a light accent, white on a deep one (accent must give ≥4.5:1 with it)
const light = {
  bg: mix(P, 0.03, WHITE), surface: WHITE, surface2: mix(P, 0.06, WHITE),
  line: mix(P, 0.08, WHITE), line2: mix(P, 0.24, WHITE),
  fg: P, fg2: mix(P, 0.62, WHITE),
  accent: A, accentSoft: mix(A, 0.14, WHITE), accentFg: mix(A, 0.75, BLACK), onAccent, bad: mix(A, 0.55, BLACK),
};
const dark = {
  bg: P, surface: darkSurface, surface2: mix(WHITE, 0.10, P),
  line: alpha(WHITE, 0.08), line2: alpha(WHITE, 0.22),
  fg: mix(P, 0.08, WHITE), fg2: mix(WHITE, 0.58, P),
  accent: A, accentSoft: mix(A, 0.22, darkSurface), accentFg: mix(A, 0.70, WHITE), onAccent, bad: mix(A, 0.65, WHITE),   // ≥4.5:1 on surface and accentSoft
};
const NAMES = Object.keys(light);

// --- formats ---------------------------------------------------------------------------------------------------
const h2 = (v) => Math.round(v).toString(16).padStart(2, '0');
const cssColor = (c) => c.a === 1 ? `#${h2(c.r)}${h2(c.g)}${h2(c.b)}` : `rgba(${Math.round(c.r)},${Math.round(c.g)},${Math.round(c.b)},${c.a})`;
const hex8 = (c) => `#${h2(c.r)}${h2(c.g)}${h2(c.b)}${h2(c.a * 255)}`;                        // Swift: #rrggbbaa
const argb = (c) => '0x' + `${h2(c.a * 255)}${h2(c.r)}${h2(c.g)}${h2(c.b)}`.toUpperCase();  // Kotlin: 0xAARRGGBB
const kebab = (n) => n.replace(/([A-Z0-9])/g, '-$1').toLowerCase();
const snake = (n) => kebab(n).replace(/-/g, '_').toUpperCase();
const cssBlock = (set) => NAMES.map((n) => `--${kebab(n)}:${cssColor(set[n])}`).join(';');

const stamp = 'generated by agent/scripts/generate-theme.mjs from agent/theme.json — do not edit';
await mkdir(new URL('../src/generated/', import.meta.url), { recursive: true });
await writeFile(new URL('../src/generated/theme-colors.css', import.meta.url),
  `/* ${stamp} */\n:root{--primary:${primary};--accent:${accent};${cssBlock(light)}}\n` +
  `@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){${cssBlock(dark)}}}\n` +
  `:root[data-theme="dark"]{${cssBlock(dark)}}\n`);

const swiftSet = (set) => NAMES.map((n) => `${n}: "${hex8(set[n])}"`).join(', ');
await writeFile(new URL('../../Ppomi/Sources/Ppomi/Views/Palette.generated.swift', import.meta.url),
  `// ${stamp}\nenum ThemeColors {\n    static let primary = "${primary}"\n    static let accent = "${accent}"\n` +
  `    struct Set { let ${NAMES.join(', ')}: String }   // #rrggbbaa\n` +
  `    static let light = Set(${swiftSet(light)})\n    static let dark = Set(${swiftSet(dark)})\n}\n`);

const kotlinSet = (set) => NAMES.map((n) => `        const val ${snake(n)} = ${argb(set[n])}`).join('\n');
await writeFile(new URL('../../Android/app/src/main/java/com/ppomi/androidbridge/ThemeColors.kt', import.meta.url),
  `// ${stamp}\npackage com.ppomi.androidbridge\n\n/** ARGB. Every UI color on Android is one of these. */\ninternal object ThemeColors {\n` +
  `    const val PRIMARY = ${argb(P)}\n    const val ACCENT = ${argb(A)}\n    object Light {\n${kotlinSet(light)}\n    }\n    object Dark {\n${kotlinSet(dark)}\n    }\n}\n`);

// Android's splash ground is XML (no color math there).
await writeFile(new URL('../../Android/app/src/main/res/values/theme_colors.xml', import.meta.url),
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${stamp} -->\n<resources>\n    <color name="ppomi_bg_light">${cssColor(light.bg).toUpperCase()}</color>\n` +
  `    <color name="ppomi_bg_dark">${cssColor(dark.bg).toUpperCase()}</color>\n</resources>\n`);
console.log(`theme: primary ${primary} accent ${accent} · on-accent ${cssColor(onAccent)} · bg ${cssColor(light.bg)}/${cssColor(dark.bg)}`);
