export {
  AuthRequest,
  DEVICE_WRAP_LEN,
  DeviceKeyPair,
  KEY_LEN,
  RECOVERY_AAD,
  RECOVERY_KDF_ALG,
  VAULT_VERSION,
  X25519_LEN,
  approveAuthRequest,
  assertKdfLimits,
  createAuthRequest,
  createDek,
  createDeviceKeyPair,
  defaultKdfLimits,
  fingerprintsMatch,
  interactiveKdfLimits,
  pairingFingerprint,
  readyVault,
  wrapDekForDevice,
  wrapDekForRecovery,
  type AuthRequestPublic,
  type KdfLimits,
  type RecoveryKdf,
  type RecoveryWrap,
} from "./crypto.ts";
export {
  KB_STAR_BIZ_ACCOUNT_KEY,
  RESERVED_KEY_PREFIX,
  ClientVault,
  MemoryCiphertextStore,
  VaultError,
  acceptAuthApproval,
  assertServerRecord,
  deviceWrapKeyId,
  openDeviceDek,
  openRecoveryDek,
  pairRequestKeyId,
  persistAuthRequest,
  persistDeviceDekWrap,
  persistRecoveryDekWrap,
  storeContainsPlaintext,
  vaultEvidence,
  type CiphertextStore,
  type DeviceDekWrapRecord,
  type PairingRequestRecord,
  type PayloadRecord,
  type RecoveryDekWrapRecord,
  type ServerRecord,
  type ServerRecordKind,
  type VaultErrorCode,
  type VaultEvidence,
  type VaultPutOptions,
} from "./vault.ts";
