// generated by agent/scripts/generate-theme.mjs from agent/theme.json — do not edit
enum ThemeColors {
    static let primary = "#111111"
    static let accent = "#2f6fe0"
    struct Set { let bg, surface, surface2, line, line2, fg, fg2, accent, accentSoft, accentFg, onAccent, bad: String }   // #rrggbbaa
    static let light = Set(bg: "#f8f8f8ff", surface: "#ffffffff", surface2: "#f1f1f1ff", line: "#ecececff", line2: "#c6c6c6ff", fg: "#111111ff", fg2: "#6b6b6bff", accent: "#2f6fe0ff", accentSoft: "#e2ebfbff", accentFg: "#2353a8ff", onAccent: "#ffffffff", bad: "#1a3d7bff")
    static let dark = Set(bg: "#111111ff", surface: "#1b1b1bff", surface2: "#292929ff", line: "#ffffff14", line2: "#ffffff38", fg: "#ecececff", fg2: "#9b9b9bff", accent: "#2f6fe0ff", accentSoft: "#1f2d46ff", accentFg: "#6d9ae9ff", onAccent: "#ffffffff", bad: "#78a1ebff")
}
