// generated by agent/scripts/generate-theme.mjs from agent/theme.json — do not edit
package com.ppomi.androidbridge

/** ARGB. Every UI color on Android is one of these. */
internal object ThemeColors {
    const val PRIMARY = 0xFF111111
    const val ACCENT = 0xFF2F6FE0
    object Light {
        const val BG = 0xFFF8F8F8
        const val SURFACE = 0xFFFFFFFF
        const val SURFACE_2 = 0xFFF1F1F1
        const val LINE = 0xFFECECEC
        const val LINE_2 = 0xFFC6C6C6
        const val FG = 0xFF111111
        const val FG_2 = 0xFF6B6B6B
        const val ACCENT = 0xFF2F6FE0
        const val ACCENT_SOFT = 0xFFE2EBFB
        const val ACCENT_FG = 0xFF2353A8
        const val ON_ACCENT = 0xFFFFFFFF
        const val BAD = 0xFF1A3D7B
    }
    object Dark {
        const val BG = 0xFF111111
        const val SURFACE = 0xFF1B1B1B
        const val SURFACE_2 = 0xFF292929
        const val LINE = 0x14FFFFFF
        const val LINE_2 = 0x38FFFFFF
        const val FG = 0xFFECECEC
        const val FG_2 = 0xFF9B9B9B
        const val ACCENT = 0xFF2F6FE0
        const val ACCENT_SOFT = 0xFF1F2D46
        const val ACCENT_FG = 0xFF6D9AE9
        const val ON_ACCENT = 0xFFFFFFFF
        const val BAD = 0xFF78A1EB
    }
}
